Three/Three/Models/CompanySummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Three.Models
{
    /// <summary>
    /// 公司情况表
    /// </summary>
    public class CompanySummary
    {
        public int EmployeeCount { get; set; }//员工总人数
        public int AverageDepartmentEmployeeCount { get; set; }//每个部门平均人数
    }
}

Three/Three/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Three.Models
{
    /// <summary>
    /// 部门表
    /// </summary>
    public class Department
        
    {
        [Display(Name = "部门id")]
        /// <summary>
        /// 部门id
        /// </summary>
        public int Id { get; set; }

        [Display(Name="部门名称")] //asp- for用法
        /// <summary>
        /// 部门名字
        /// </summary>
        
        public string Name { get; set; }
        [Display(Name = "部门地区")]
        /// <summary>
        /// 部门地区
        /// </summary>
        public string Location { get; set; }
        [Display(Name = "员工人数")]
        /// <summary>
        /// 员工人数
        /// </summary>
        public int EmployeeCount { get; set; }

    }
}

Three/Three/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Three.Models
{
    /// <summary>
    /// 员工表
    /// </summary>
    public class Employee
    {
        
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Gender Gender { get; set; }
        public bool Fired { get; set; }
    }

    public enum Gender{
        male = 1,
        female = 0
    }
}

Three/Three/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Three.Services;
using Three.Models;
using Microsoft.Extensions.Options;
using Three.Service;

namespace Three.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

       // 用于检索已配置的选项实例。
        private readonly IOptions<ThreeOptions> _threeOptions;

        public IOptions<ThreeOptions> ThreeOptions { get; }

        public DepartmentController(IDepartmentService departmentService, IOptions<ThreeOptions> threeOptions)
        {
            _departmentService = departmentService;
            _threeOptions = threeOptions;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Department Index";
            var departments = await _departmentService.GetAll();
            return View(departments);
        }

        //[HTTPGet]
        public IActionResult Add()
        {
            ViewBag.Title = "添加员工";
            return View(new Department());
        }
        [HttpPost]
        public async Task<IActionResult> Add(Department m)
        {
            if (ModelState.IsValid)
            {
                await _departmentService.Add(m);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Three/Three/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Three.Models;
using Three.Service;
using Three.Services;

namespace Three.Controllers
{
    public class EmployeeController : Controller
    {
        //定义两个只读的操作接口字段
        private readonly IDepartmentService _departmentService;
        private readonly IEmployeeService _employeeService;

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="departmentService"></param>
        /// <param name="employeeService"></param>
        public EmployeeController(IDepartmentService departmentService, IEmployeeService employeeService)
        {
            _departmentService = departmentService;
            _employeeService = employeeService;
        }

        public async Task<IActionResult> Index(int departmentId)
        {
            var department = await this._departmentService.GetById(departmentId);//通过部门id查找部门人数
           ViewBag.Title = $"Employee of {department.Name}";
            ViewBag.DepartmentId = departmentId;
            var employees = await _employeeService.GetByDepartmentId(departmentId);//查询部门下员工信息
            return View(employees);
        }
        
        public IActionResult Add(int departmentId)
        {
            ViewBag.Title = "Add Employee";
            return View(new Employee
            {
                DepartmentId = departmentId
            });
        }

        [HttpPost]
        public async Task<IActionResult> Add(Employee model)
        {
            if (ModelState.IsValid)
            {
                await _employeeService.Add(model);
            }
            return RedirectToAction(nameof(Index), new { departmentId = model.DepartmentId });
        }

        public async Task<IActionResult> Fire(int employeeId)
        {
            var employee = await _employeeService.Fire(employeeId);
            return RedirectToAction(nameof(Index), new { departmentId = employee.DepartmentId });
        }

    }
}

Three/Three/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Three.Service;

namespace Three.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(IClock clock)
        {

        }
        public IActionResult Index()
        {
            return View();
        }

       
    }
}

Three/Three/ViewComponents/CompanySummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Three.Service;
using Three.Services;

namespace Three.ViewComponents
{
    public class CompanySummaryViewComponent : ViewComponent
    {
        /// <summary>
        /// 定义只读操作部门类
        /// </summary>
        private readonly IDepartmentService _departmentService;

        /// <summary>
        /// 构造
        /// </summary>
        /// <param name="departmentService"></param>
        public CompanySummaryViewComponent(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }
        /// <summary>
        /// 异步调用
        /// </summary>
        /// <param name="title"></param>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(string title)
        {
            ViewBag.Title = title;
            var summary = await _departmentService.GetCompanySummary();
            return View(summary);
        }
    }
}

Three/Three/Views/Department/DisplayTemplates/Department.cshtml
@using Microsoft.Extensions.Options
@using Three
@model Three.Models.Department
@inject IOptions<ThreeOptions> options
@*注入*@

    <tr>
        @*判断人数是否>30，如果大于字体变粗*@
        @if (Model.EmployeeCount > options.Value.BoldDepartmentEmployeeCountThreshold)
        {
            <td><strong>@Model.Name</strong></td>
        }
        else { 
            <td>@Model.Name</td>
        }
        <td>@Model.Location</td>
        <td>@Model.EmployeeCount</td>
        <td>
            <a asp-controller="Employee" asp-action="Index" asp-route-departmentId="@Model.Id">
                Employees
            </a>
        </td>
    </tr>

Three/Three/Views/Department/Index.cshtml
@using Three.Models;
@model IEnumerable<Department>

<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Employee Count</th>
                <th>Action</th>
            </tr>
            @*显示模型*@
            @Html.DisplayForModel()
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        @await Component.InvokeAsync("CompanySummary", new { title = "部门列表页"})
        <vc:company-summary title="汇总2"></vc:company-summary>
    </div>
    <div class="col-md-4 offset-md-2">
        @*指定需要的action名字*@
        <a asp-action="Add">Add</a>
    </div>
</div>

Three/Three/Views/Employee/Add.cshtml
@using Three.Models
@model Employee

    <form asp-action="Add">
        <input type="hidden" asp-for="DepartmentId" />

        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="FirstName"></label>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="FirstName" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="LastName"></label>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="LastName" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="Gender"></label>
            </div>
            <div class="col-md-6">
                <select class="form-control" asp-for="Gender" 
                        asp-items="Html.GetEnumSelectList<Gender>()">

                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </div>
    </form>

Three/Three/Views/Employee/DisplayTemplates/Employee.cshtml
@model Three.Models.Employee

    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.LastName</td>
        <td>@Model.Gender</td>
        <td>@(Model.Fired ? "YES" : "")</td>
        <td>
        @if (!Model.Fired) { 
            <a asp-action="Fire" asp-route-employeeId="@Model.Id">
                Fire
            </a>
        }</td>
    </tr>

Three/Three/Views/Shared/Components/CompanySummary/Default.cshtml
@using Three.Models
@model CompanySummary

    <div class="small">
        <div class="row h3">@ViewBag.Title</div>
        <div class="row">
            <div class="col-md-8">员工总数</div>
            <div class="col-md-4">@Model.EmployeeCount</div>
        </div>
        <div class="row">
        <div class="col-md-8">部门平均人数</div>
        <div class="col-md-4">@Model.AverageDepartmentEmployeeCount</div>
    </div>
</div>